services:
    module_cart.cart.creator:
        class: Module\Cart\Service\Create\CartCreator
        arguments: ["@module_cart.cart.repository.mysql"]

    module_cart.cart.remover:
        class: Module\Cart\Service\Remove\CartRemover
        arguments: ["@module_cart.cart.repository.mysql", "@module_cart.cart.item.repository.mysql"]

    module_cart.cart.total.amount.calculator:
        class: Module\Cart\Service\Calculator\CartTotalAmountCalculator
        arguments: ["@module_cart.cart.item.repository.mysql"]

    module_cart.cart.total.amount.by.seller.calculator:
        class: Module\Cart\Service\Calculator\CartTotalAmountBySellerCalculator
        arguments: ["@module_cart.cart.item.repository.mysql"]

    module_cart.cart.item.creator:
        class: Module\Cart\Service\Create\CartItemCreator
        arguments: ["@module_cart.cart.item.repository.mysql"]

    module_cart.cart.item.remover:
        class: Module\Cart\Service\Remove\CartItemRemover
        arguments: ["@module_cart.cart.item.repository.mysql"]

    module_cart.cart.items.by.cart.id.finder:
        class: Module\Cart\Service\Finder\CartItemsByCartIdFinder
        arguments: ["@module_cart.cart.item.repository.mysql"]