AppBundle\Entity\CartItem:
    type: entity
    table: cart_item

    id:
        id:
            type: string
            id: true

    fields:
        cartId:
            type: string
            column: cart_id
        sellerProductId:
            type: integer
            column: seller_product_id
        quantity:
            type: integer

    lifecycleCallbacks: {  }
