AppBundle\Entity\CartLine:
    type: entity
    table: cart_line

    id:
        id:
            type: integer
            id: true
            options:
                unsigned: true
            generator:
                strategy: AUTO

    fields:
        cartId:
            type: integer
            column: cart_id
        sellerProductId:
            type: integer
            column: seller_product_id
        quantity:
            type: integer

    lifecycleCallbacks: {  }
