AppBundle\Entity\Orders:
    type: entity
    table: orders

    id:
        id:
            type: string
            id: true

    fields:
        cartId:
            type: string
            column: cart_id
        paymentId:
            type: integer
            column: payment_id
        totalAmount:
            type: decimal
            precision: 10
            scale: '2'
            column: total_amount
        status:
            type: string
            columnDefinition: ENUM('pending', 'shipping', 'delivered')

    lifecycleCallbacks: {  }
