AppBundle\Entity\Payment:
    type: entity
    table: payment

    id:
        id:
            type: integer
            id: true
            options:
                unsigned: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 255

    lifecycleCallbacks: {  }
