AppBundle\Entity\Product:
    type: entity
    table: product

    id:
        id:
            type: integer
            id: true
            options:
                unsigned: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 255
        createdAt:
            type: datetime
            column: created_at

    lifecycleCallbacks:
        prePersist: [setCreatedAtValue]
